services:
  atomspace-api:
    image: abdum1964/atomspace-api:latest
    container_name: atomspace-api
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - API_PORT=${API_PORT:-8000}
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_HTTP_PORT=7474
      - NEO4J_BOLT_PORT=7687
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_API_KEY=${LLM_API_KEY}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-atomspace123}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}
      - HUGEGRAPH_HOST=hugegraph
      - HUGEGRAPH_PORT=${HUGEGRAPH_PORT:-8080}
      - HUGEGRAPH_GRAPH=${HUGEGRAPH_GRAPH:-hugegraph}
      - ANNOTATION_SERVICE_URL=${ANNOTATION_SERVICE_URL:-}
      - ANNOTATION_SERVICE_TIMEOUT=${ANNOTATION_SERVICE_TIMEOUT:-300.0}
    volumes:
      - ./output:/app/output
      - ./config.yaml:/app/config.yaml
      - atomspace_logs:/app/logs
      - shared_output:/shared/output
    depends_on:
      hugegraph:
        condition: service_started
    networks:
      - atomspace-network
    restart: always

  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-atomspace
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-atomspace123}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_directories_import=/var/lib/neo4j/import
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_INITIAL:-512m}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MAX:-2G}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_PAGECACHE:-1G}
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - shared_output:/var/lib/neo4j/import/shared/output
      - neo4j_plugins:/plugins
    networks:
      - atomspace-network
    restart: unless-stopped


  hugegraph:
    image: hugegraph/hugegraph:1.5.0
    container_name: hugegraph-atomspace
    ports:
      - "${HUGEGRAPH_REST_PORT:-8080}:8080"
      - "${HUGEGRAPH_GREMLIN_PORT:-8182}:8182"
    environment:
      - HUGEGRAPH_CONF=/hugegraph/conf
    volumes:
      - hugegraph_data:/hugegraph/data
      - hugegraph_logs:/hugegraph/logs
    networks:
      - atomspace-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  hugegraph_data:
  hugegraph_logs:
  atomspace_logs:
  shared_output:

networks:
  atomspace-network:
    driver: bridge
