name: Bug report (Bug)
description: Create a bug report to help Custom Atomspace Builder improve
title: '[Bug] describe the main problem'
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **Note**:
        We need as much detailed information as possible to reproduce the problem, the more detailed information (including logs/screenshots/configurations, etc.) will be responded and processed faster.

