name: Ask question
description: Question about usage or configs in Custom Atomspace Builder
title: '[Question] describe your problem'

body:
  - type: markdown
    attributes:
      value: |
        **Note**:
        We need as much detailed information as possible to reproduce the problem, the more detailed information (including logs/screenshots/configurations, etc.) will be responded and processed faster.
        
